#!/bin/bash
script_parameters="[-h] [-f <file>] [-r <replicates>] [-p <ppis>] [-t <hubs>] [-i <interactions>] [-d <directory>]"
i=1
for a in ${@};
do
((i=i+1))
if [ "$a" = "-h" ] || [ "$a" = "--help" ]
then
echo "cluster2hub identifies transcription factors, kinases and other proteins as hubs in the network of optimal gene co-expression cluster." $'\n'
echo "Usage: `basename $0` $script_parameters"
echo "positional arguments:"
echo "	-f <file>			Input expression file"
echo "	-p <ppis>			Protein-proteins interactions file"
echo "optional arguments:"
echo "	-h, --help			Shows this help message and exit"
echo "	-r <replicates>			Replicates structure file"
echo "	-t <hubs>			Percent of top degree nodes" 
echo "	-i <interactions>		Drug gene interactions file" 
echo "	-d <directory>			Output directory"
exit
fi
done

if [ $# -le 3 ]
then
echo "Usage: `basename $0` $script_parameters"
exit
fi
#echo "`basename $0` $@"

i=1
for a in ${@};
do
((i=i+1))
if [ "$a" = "-f" ]
then
file=${@:$i:1}
fi
done
if [ ! -e "$file" ]
then
echo "Expression file $file does not exist.";
exit
fi

replicates=NA
i=1
for a in ${@};
do
((i=i+1))
if [ "$a" = "-r" ]
then
replicates=${@:$i:1}
fi
done
if [ $replicates = NA ]
then
echo
else
if [ ! -e "$replicates" ]
then
echo "Replicates file $replicates does not exist.";
exit
fi
fi

i=1
for a in ${@};
do
((i=i+1))
if [ "$a" = "-p" ]
then
ppis=${@:$i:1}
fi
done
if [ ! -e "$ppis" ]
then
echo "PPIs file $ppis does not exist.";
exit
fi

top=5
i=1
for a in ${@};
do
((i=i+1))
if [ "$a" = "-t" ]
then
top=${@:$i:1}
fi
done

dgi=NA
i=1
for a in ${@};
do
((i=i+1))
if [ "$a" = "-i" ]
then
dgi=${@:$i:1}
fi
done
if [ $dgi = NA ]
then
echo
else
if [ ! -e "$dgi" ]
then
echo "Drug gene interactions file $dgi does not exist.";
exit
fi
fi

directory=0
i=1
for a in ${@};
do
((i=i+1))
if [ "$a" = "-d" ]
then
directory=${@:$i:1}
fi
done
if [ $directory = 0 ]
then
rm -rf -R "cluster2hub_out"
directory="cluster2hub_out"
mkdir $directory
else
if [ ! -e "$directory" ]
then
mkdir $directory
else
echo "Directory $directory already exist.";
fi
fi

echo $'\n'

echo "Input expression file is : $file"
echo "Replicates structure file is : $replicates"
echo "Protein-proteins interactions file is : $ppis"
echo "Percent of top degree nodes is : $top"
echo "Drug gene interactions file is : $dgi"
echo "Output directory is : $directory"

if [ $replicates = "NA" ]
then
echo "Extracting optimal co-expressed gene clusters ... "
clust $file -o $directory/Clusters
else
echo "Extracting optimal co-expressed gene clusters ... "
clust $file -r $replicates -o $directory/Clusters
fi
mv $directory/Clusters/Clusters_Objects.tsv $directory
mv $directory/Clusters/Clusters_profiles.pdf $directory
echo "Enriching transcription factors in the clusters ... "
mkdir "$directory/Tfs"
Tfs.R $directory
Tfs_all.pl $directory
echo "Enriching kinases of the transcription factors in the clusters ... "
mkdir "$directory/Kinases"
Kinases.R $directory
Kinases_all.pl $directory
echo "Extracting protein-protein interactions of transcription factors, kinases and other proteins in the clusters ... "
Tfs_all_ppis.pl $directory $ppis
Kinases_all_ppis.pl $directory $ppis
echo "Building protein interactions networks ... "
mkdir "$directory/Networks"
Networks.R $directory $top
echo "Enriching networks proteins in Gene Ontology and KEGG pathways ... "
mkdir "$directory/Go_kegg"
Go_kegg.R $directory
echo "Extracting chemicals for hubs from $dgi ... "
Dgi.pl $directory $dgi

