#!/usr/local/bin/Rscript
args=commandArgs(trailingOnly=TRUE)
bag<-args[1]
t<-as.numeric(args[2])
file<-paste(bag,"Clusters_Objects.tsv",sep="/")
clusters_data<-read.table(file,sep="\t",header=T)
nclust<-length(colnames(clusters_data))
setwd(paste(bag,"Networks",sep="/"))
library(igraph)
for(i in 1:nclust)
{
	file_tfs_ppis<-paste("..",paste("Cluster",i-1,"Tfs_all_ppis.txt",sep="_"),sep="/")
	tf_ppis<-read.table(file_tfs_ppis,sep="\t",header=F)
	file_ks_ppis<-paste("..",paste("Cluster",i-1,"Kinases_all_ppis.txt",sep="_"),sep="/")
	k_ppis<-read.table(file_ks_ppis,sep="\t",header=F)
	ppis<-rbind(tf_ppis,k_ppis)
	ppis_1<-ppis
	file_tfs<-paste("..",paste("Cluster",i-1,"Tfs_all.txt",sep="_"),sep="/")
	tfs_data<-read.table(file_tfs,sep="\t",header=T)
	tfs_data_1<-tfs_data
	file_ks<-paste("..",paste("Cluster",i-1,"Kinases_all.txt",sep="_"),sep="/")
	ks_data<-read.table(file_ks,sep="\t",header=T)
	ks_data_1<-ks_data
	genes_i<-unique(clusters_data[,i])
	nodes_i<-unique(c(ppis[,1],ppis[,2]))
	ks<-which(nodes_i%in%ks_data$Term==TRUE)
	tfs<-which(nodes_i%in%tfs_data$Term==TRUE)
	p<-which(nodes_i%in%genes_i==TRUE)
	kstfsp<-c(ks,tfs,p)
	kstfsp_uniq<-unique(sort(kstfsp))
	others<-which(1:length(nodes_i)%in%kstfsp_uniq==FALSE)
	colrs<-c()
	colrs[others]<-"grey"
	colrs[p]<-"green"
	colrs[tfs]<-"pink"
	colrs[ks]<-"blue"
	p_type<-c()
	p_type[others]<-"Others"
	p_type[p]<-"Interacting_protein"
	p_type[tfs]<-"Transcription_factor"
	p_type[ks]<-"Kinase"
	g<-graph_from_data_frame(ppis,directed=F)
	g2<-simplify(g)
	denom<-length(names(V(g2)))/length(which(degree(g2)>2))
	V(g2)$size<-1+(degree(g2)/denom)
	V(g2)$color<-colrs
	V(g2)$frame.color<-colrs
	out_ntwk<-paste("Cluster",i-1,"Network.pdf",sep="_")
	pdf(out_ntwk)
	lcex=(length(names(V(g2)))-length(which(degree(g2)<=3)))/(length(names(V(g2))))
	ewid=(length(names(V(g2)))-length(which(degree(g2)<=3)))/(length(names(V(g2))))
	plot(g2,vertex.label.cex=lcex,edge.width=ewid)
	dev.off()
	print(paste("Identifying hubs in the protein interactions networks of Cluster ",i-1," ... ",sep=""))
	deg<-degree(g2,mode="all")
	deg_colrs<-data.frame(names(deg),deg,colrs)
	deg_colrs_type<-cbind(deg_colrs,p_type)
	colnames(deg_colrs_type)<-c("Node","Degree","Color","Type")
	deg_colrs_type2<-deg_colrs_type[order(deg_colrs_type$Degree,decreasing=TRUE),]
	cut_deg<-deg_colrs_type2[round((t*length(names(V(g2))))/100),]$Degree
	hubs<-deg_colrs_type2[deg_colrs_type2$Degree>=cut_deg,]
	ttl<-c("Node","Degree","Color","Type")
	deg_colrs_type3<-rbind(ttl,deg_colrs_type2)
	out_dd<-paste("Cluster",i-1,"Network_DD.txt",sep="_")
	write.table(deg_colrs_type3,out_dd,sep="\t",quote=F,col.names=F,row.names=F)
	hubs2<-rbind(ttl,hubs)
	out_hub<-paste("Cluster",i-1,"Network_Hubs.txt",sep="_")
	write.table(hubs2,out_hub,sep="\t",quote=F,col.names=F,row.names=F)
	file.copy(out_ntwk,"../",overwrite=TRUE)
	file.copy(out_dd,"../",overwrite=TRUE)
	file.copy(out_hub,"../",overwrite=TRUE)
}
